// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Family struct {
	ID          int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	Name        string
	Description string
}

type Photo struct {
	ID         string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
	Name       string
	AltText    string
	Url        string
	ThumbUrl   string
	UserID     string
	PostID     pgtype.Int8
}

type Post struct {
	ID              int64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Description     string
	FeaturedPhotoID pgtype.Text
	UserID          string
	FamilyID        int64
}

type User struct {
	ID        string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Name      string
	Apikey    string
	FamilyID  pgtype.Int8
	Password  string
}
