// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Family struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description string
}

type Photo struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ModifiedAt time.Time
	Name       string
	AltText    string
	Url        string
	ThumbUrl   string
	UserID     string
	PostID     sql.NullInt64
}

type Post struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Description     string
	FeaturedPhotoID sql.NullString
	UserID          string
	FamilyID        int64
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Apikey    string
	FamilyID  sql.NullInt64
	Password  string
}
