// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Photo struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ModifiedAt time.Time
	Name       string
	AltText    string
	Url        string
	ThumbUrl   string
	UserID     string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Apikey    string
}
