version: '3'

dotenv: ['.env']

tasks:
  prod:
    desc: Start server
    cmds:
      - go build && ./phamily-photos
  dev:
    desc: Start air to auto-rebuild and restart the Go app on file changes
    cmds:
      - air
    interactive: true

  db:migrate:
    desc: run migrations with goose
    cmds:
      - goose up
    interactive: true

  db:drop:
    desc: Drop database and user
    cmds:
      - psql -h localhost -U postgres -c "DROP DATABASE {{.NEW_DB_NAME}};"
      - psql -h localhost -U postgres -c "DROP USER {{.NEW_DB_USER}};"
    vars:
      NEW_DB_USER: phamilyphotos
      NEW_DB_PASSWORD: phamilyphotos
      NEW_DB_NAME: phamily_photos
    env:
      PGPASSWORD: '{{.POSTGRES_PGPASSWORD}}'
    interactive: true

  db:init:
    desc: Create PostgreSQL user and initialize the database
    cmds:
      - psql -h localhost -U postgres -c "CREATE USER {{.NEW_DB_USER}} WITH PASSWORD '{{.NEW_DB_PASSWORD}}';"
      - psql -h localhost -U postgres -c "CREATE DATABASE {{.NEW_DB_NAME}} OWNER {{.NEW_DB_USER}};"
      - psql -h localhost -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE {{.NEW_DB_NAME}} TO {{.NEW_DB_USER}};"
      - psql -h localhost -U postgres -d {{.NEW_DB_NAME}} -c "GRANT ALL ON SCHEMA public TO {{.NEW_DB_USER}};" 
    vars:
      NEW_DB_USER: phamilyphotos
      NEW_DB_PASSWORD: phamilyphotos
      NEW_DB_NAME: phamily_photos
    env:
      PGPASSWORD: '{{.POSTGRES_PGPASSWORD}}'
    interactive: true

  db:seed:
    desc: Seed database with initial familiy (start the server in separate terminal before running)
    cmds:
      - psql -h localhost -U {{.NEW_DB_USER}} -d {{.NEW_DB_NAME}} -c "INSERT INTO families (id, created_at, updated_at, name, description) VALUES (1, NOW(), NOW(), '{{.INITIAL_FAMILY_NAME}}', 'Your family')"
      - |
        curl -X POST localhost:{{.PORT}}/v1/users \
          -H "Content-Type: application/json" \
          -d '{"name": "{{.INITIAL_USER_NAME}}", "password": "{{.INITIAL_USER_PASSWORD}}", "family_id": 1}'
    env:
      PGPASSWORD: '{{.NEW_DB_PASSWORD}}'
    vars:
      NEW_DB_USER: phamilyphotos
      NEW_DB_PASSWORD: phamilyphotos
      NEW_DB_NAME: phamily_photos
    interactive: true
